version: '3.8'

services:

  dbpostgres:
    image: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "15432:5432"
    volumes:
      - ./dbpostgres:/var/lib/postgresql/data 

volumes:
  dbpostgres: